# Generated by Django 6.0.3 on 2026-03-17 18:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('email_alerts', models.BooleanField(default=True)),
                ('email_on_trade', models.BooleanField(default=True)),
                ('email_on_error', models.BooleanField(default=True)),
                ('dashboard_theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=20)),
                ('nlp_enabled', models.BooleanField(default=True)),
                ('nlp_model', models.CharField(default='claude-3-5-sonnet-20241022', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'accounts_userprofile',
            },
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('broker', models.CharField(choices=[('oanda', 'OANDA'), ('metatrader5', 'MetaTrader 5'), ('demo', 'Demo (Paper Trading)')], max_length=30)),
                ('account_id', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('live', 'Live Trading'), ('demo', 'Demo / Paper')], default='demo', max_length=10)),
                ('_api_key_encrypted', models.TextField(blank=True, db_column='api_key')),
                ('_api_secret_encrypted', models.TextField(blank=True, db_column='api_secret')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('equity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('margin_used', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('margin_free', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Account',
                'verbose_name_plural': 'Trading Accounts',
                'db_table': 'accounts_tradingaccount',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_verified'], name='accounts_us_is_acti_0584df_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingaccount',
            index=models.Index(fields=['user', 'broker'], name='accounts_tr_user_id_f49315_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingaccount',
            index=models.Index(fields=['is_active'], name='accounts_tr_is_acti_a606bc_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingaccount',
            index=models.Index(fields=['broker', 'account_id'], name='accounts_tr_broker_0bb5e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradingaccount',
            unique_together={('user', 'broker', 'account_id')},
        ),
    ]
