# Generated by Django 6.0.3 on 2026-03-30 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_portfolio_multi_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountallocation',
            options={'verbose_name': 'Account Allocation', 'verbose_name_plural': 'Account Allocations'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_accounts', to='accounts.portfolio'),
        ),
    ]
