# Generated by Django 6.0.3 on 2026-04-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountallocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('funded', 'Funded Account'), ('demo', 'Demo / Practice'), ('contest', 'Contest')], default='demo', max_length=10),
        ),
    ]
