# Generated by Django 6.0.3 on 2026-04-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_broker_type_account_type_funded'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='broker_type',
            field=models.CharField(choices=[('oanda', 'OANDA'), ('mt5', 'MetaTrader 5'), ('other', 'Other')], default='oanda', help_text='Broker connector type (OANDA REST or MT5)', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='daily_loss_limit',
            field=models.FloatField(blank=True, help_text='Daily max drawdown limit (USD) — funded account rule', null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='funded_firm',
            field=models.CharField(blank=True, choices=[('ftmo', 'FTMO'), ('mff', 'MyForexFunds'), ('true_forex', 'True Forex Funds'), ('funded_next', 'FundedNext'), ('alpha_capital', 'Alpha Capital Group'), ('e8_funding', 'E8 Funding'), ('other', 'Other'), ('', 'N/A')], default='', help_text='Funded firm name (FTMO, MFF, etc.) — leave blank for personal', max_length=30),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='max_loss_limit',
            field=models.FloatField(blank=True, help_text='Maximum allowed loss for funded accounts (USD)', null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='profit_target',
            field=models.FloatField(blank=True, help_text='Profit target for funded account challenge (USD)', null=True),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('funded', 'Funded Account'), ('demo', 'Demo / Practice'), ('contest', 'Contest')], default='demo', help_text='Account category — personal, funded, demo', max_length=20),
        ),
    ]
