# Generated by Django 6.0.3 on 2026-04-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tradingaccount_broker_type_and_more'),
    ]

    operations = [
    ]
