# Generated by Django 6.0.3 on 2026-04-10 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_manual_sync_phase3'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('breakeven_trades', models.PositiveIntegerField(default=0)),
                ('total_pips', models.FloatField(default=0.0, help_text='Net pips across all closed trades (+ = profit)')),
                ('total_pips_won', models.FloatField(default=0.0, help_text='Total pips from winning trades only')),
                ('total_pips_lost', models.FloatField(default=0.0, help_text='Total pips from losing trades (positive number)')),
                ('avg_win_pips', models.FloatField(default=0.0)),
                ('avg_loss_pips', models.FloatField(default=0.0)),
                ('largest_win_pips', models.FloatField(default=0.0)),
                ('largest_loss_pips', models.FloatField(default=0.0)),
                ('total_profit', models.FloatField(default=0.0, help_text='Net P&L in account currency across all trades')),
                ('gross_profit', models.FloatField(default=0.0)),
                ('gross_loss', models.FloatField(default=0.0, help_text='Stored as positive number')),
                ('largest_win', models.FloatField(default=0.0)),
                ('largest_loss', models.FloatField(default=0.0, help_text='Stored as positive number')),
                ('avg_win', models.FloatField(default=0.0)),
                ('avg_loss', models.FloatField(default=0.0)),
                ('win_rate', models.FloatField(default=0.0, help_text='Win rate as percentage 0–100')),
                ('profit_factor', models.FloatField(default=0.0, help_text='gross_profit / gross_loss (0 if no losses)')),
                ('expectancy', models.FloatField(default=0.0, help_text='Average expected profit per trade in account currency')),
                ('avg_rrr_used', models.FloatField(default=0.0, help_text='Average RRR set at entry across all trades')),
                ('avg_rrr_achieved', models.FloatField(default=0.0, help_text='Average RRR actually achieved at close')),
                ('max_drawdown_pct', models.FloatField(default=0.0, help_text='Maximum drawdown as % of peak balance')),
                ('max_drawdown_usd', models.FloatField(default=0.0, help_text='Maximum drawdown in USD')),
                ('current_drawdown', models.FloatField(default=0.0)),
                ('peak_balance', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0, help_text='Positive = win streak, negative = loss streak')),
                ('longest_win_streak', models.PositiveIntegerField(default=0)),
                ('longest_loss_streak', models.PositiveIntegerField(default=0)),
                ('symbol_stats', models.JSONField(blank=True, default=dict, help_text='Dict keyed by symbol with per-symbol metrics')),
                ('first_trade_at', models.DateTimeField(blank=True, null=True)),
                ('last_trade_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='accounts.tradingaccount')),
            ],
            options={
                'verbose_name': 'Account Performance',
                'db_table': 'accounts_performance',
            },
        ),
        migrations.CreateModel(
            name='AccountPerformanceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('balance', models.FloatField(default=0.0)),
                ('equity', models.FloatField(default=0.0)),
                ('daily_pnl', models.FloatField(default=0.0)),
                ('daily_pips', models.FloatField(default=0.0)),
                ('daily_trades', models.PositiveIntegerField(default=0)),
                ('daily_win_rate', models.FloatField(default=0.0)),
                ('drawdown_pct', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='accounts.tradingaccount')),
            ],
            options={
                'db_table': 'accounts_performance_history',
                'ordering': ['-snapshot_date'],
                'unique_together': {('account', 'snapshot_date')},
            },
        ),
    ]
