# Generated by Django 6.0.3 on 2026-03-17 18:10

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('broker', models.CharField(choices=[('oanda', 'OANDA'), ('metatrader5', 'MetaTrader 5'), ('demo', 'Demo (Paper Trading)')], max_length=30)),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, help_text="Pairs this bot trades, e.g. ['EUR_USD', 'GBP_USD']")),
                ('timeframe', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('M30', '30 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '1 Day'), ('W1', '1 Week'), ('MN1', '1 Month')], default='H1', max_length=5)),
                ('risk_settings', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('error', 'Error'), ('backtesting', 'Backtesting')], db_index=True, default='idle', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('current_drawdown', models.FloatField(default=0.0)),
                ('peak_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_buy', models.BooleanField(default=True)),
                ('allow_sell', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='strategies.strategy')),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='accounts.tradingaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Bot',
                'verbose_name_plural': 'Trading Bots',
                'db_table': 'trading_bot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broker_order_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('broker_trade_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('order_type', models.CharField(choices=[('buy', 'Buy (Long)'), ('sell', 'Sell (Short)'), ('buy_limit', 'Buy Limit'), ('sell_limit', 'Sell Limit'), ('buy_stop', 'Buy Stop'), ('sell_stop', 'Sell Stop')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('partial', 'Partially Filled')], db_index=True, default='pending', max_length=20)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)])),
                ('units', models.IntegerField(default=0)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('trailing_stop', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('profit_loss_pips', models.FloatField(default=0.0)),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('swap', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('signal_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of indicator values at signal time')),
                ('opened_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='accounts.tradingaccount')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.tradingbot')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trading_trade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NLPCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_command', models.TextField(help_text='Exact text the user typed')),
                ('command_type', models.CharField(choices=[('start_bot', 'Start Bot'), ('stop_bot', 'Stop Bot'), ('pause_bot', 'Pause Bot'), ('set_risk', 'Set Risk Parameters'), ('set_strategy', 'Set Strategy'), ('open_trade', 'Open Trade'), ('close_trade', 'Close Trade'), ('close_all', 'Close All Positions'), ('run_backtest', 'Run Backtest'), ('get_status', 'Get Status'), ('set_timeframe', 'Set Timeframe'), ('set_pairs', 'Set Trading Pairs'), ('unknown', 'Unknown Command')], default='unknown', max_length=30)),
                ('parsed_intent', models.JSONField(default=dict, help_text="Structured intent extracted by AI, e.g. {'action': 'set_risk', 'risk_percent': 1.5}")),
                ('ai_explanation', models.TextField(blank=True, help_text='Human-readable explanation of what the AI understood')),
                ('confidence', models.FloatField(default=0.0, help_text='AI confidence score 0–1', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial'), ('rejected', 'Rejected (Risk / Permission)')], default='pending', max_length=20)),
                ('execution_result', models.JSONField(blank=True, default=dict, help_text='What actually happened when the command was applied')),
                ('error_detail', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nlp_commands', to=settings.AUTH_USER_MODEL)),
                ('bot', models.ForeignKey(blank=True, help_text='Null means command targets all bots or is global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nlp_commands', to='trading.tradingbot')),
            ],
            options={
                'verbose_name': 'NLP Command',
                'verbose_name_plural': 'NLP Commands',
                'db_table': 'trading_nlpcommand',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('event_type', models.CharField(choices=[('signal', 'Strategy Signal'), ('order_placed', 'Order Placed'), ('order_filled', 'Order Filled'), ('order_rejected', 'Order Rejected'), ('order_closed', 'Order Closed'), ('risk_block', 'Risk Rule Blocked'), ('status_change', 'Status Changed'), ('nlp_command', 'NLP Command'), ('error', 'Error'), ('market_data', 'Market Data'), ('heartbeat', 'Heartbeat')], max_length=30)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Extra structured data (prices, indicator values, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='trading.trade')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trading.tradingbot')),
            ],
            options={
                'verbose_name': 'Bot Log',
                'verbose_name_plural': 'Bot Logs',
                'db_table': 'trading_botlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='tradingbot',
            index=models.Index(fields=['user', 'status'], name='trading_bot_user_id_319057_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingbot',
            index=models.Index(fields=['status'], name='trading_bot_status_6a4c54_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingbot',
            index=models.Index(fields=['broker', 'status'], name='trading_bot_broker_256df0_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingbot',
            index=models.Index(fields=['is_active'], name='trading_bot_is_acti_049e00_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['bot', 'status'], name='trading_tra_bot_id_a114c6_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['bot', 'symbol'], name='trading_tra_bot_id_67e568_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol', 'opened_at'], name='trading_tra_symbol_37001a_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['status', 'opened_at'], name='trading_tra_status_2da06b_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trading_account', 'status'], name='trading_tra_trading_aa0707_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['broker_order_id'], name='trading_tra_broker__118367_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpcommand',
            index=models.Index(fields=['user', 'created_at'], name='trading_nlp_user_id_043e67_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpcommand',
            index=models.Index(fields=['bot', 'created_at'], name='trading_nlp_bot_id_50f2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpcommand',
            index=models.Index(fields=['command_type', 'status'], name='trading_nlp_command_adef5b_idx'),
        ),
        migrations.AddIndex(
            model_name='nlpcommand',
            index=models.Index(fields=['status'], name='trading_nlp_status_c8d10d_idx'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['bot', 'timestamp'], name='trading_bot_bot_id_781d15_idx'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['bot', 'level'], name='trading_bot_bot_id_09c99c_idx'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['bot', 'event_type'], name='trading_bot_bot_id_6b393d_idx'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='trading_bot_event_t_b41969_idx'),
        ),
    ]
