# Generated by Django 6.0.3 on 2026-04-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='account_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit_pips',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='rrr_achieved',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='rrr_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='sl_pips',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp_pips',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
