# Generated by Django 6.0.3 on 2026-04-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_manual_sync_phase3'),
        ('trading', '0002_trade_account_label_trade_profit_pips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trading_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='accounts.tradingaccount'),
        ),
    ]
