# Generated by Django 6.0.3 on 2026-03-17 18:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_percent', models.FloatField(default=1.0, help_text='% of account balance to risk per trade (0.01–10)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)])),
                ('max_lot_size', models.DecimalField(decimal_places=2, default=1.0, help_text='Hard ceiling on lot size regardless of risk calc', max_digits=8)),
                ('min_lot_size', models.DecimalField(decimal_places=2, default=0.01, max_digits=8)),
                ('stop_loss_pips', models.FloatField(default=50.0, help_text='Default SL in pips if strategy does not specify', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('take_profit_pips', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('risk_reward_ratio', models.FloatField(default=2.0, help_text='If set, TP = SL * risk_reward_ratio (overrides take_profit_pips)')),
                ('use_risk_reward', models.BooleanField(default=False)),
                ('trailing_stop_enabled', models.BooleanField(default=False)),
                ('trailing_stop_pips', models.FloatField(default=20.0)),
                ('trailing_step_pips', models.FloatField(default=5.0)),
                ('max_trades_per_day', models.PositiveIntegerField(default=10)),
                ('max_daily_loss', models.FloatField(default=5.0, help_text='Max % account loss in a single day before halting bot')),
                ('max_daily_profit', models.FloatField(default=0.0, help_text='0 = disabled. Stop bot when daily profit reaches this %')),
                ('max_drawdown_percent', models.FloatField(default=20.0, help_text='Halt bot permanently if drawdown exceeds this %', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)])),
                ('drawdown_pause_percent', models.FloatField(default=10.0, help_text='Pause (not stop) bot at this % drawdown — resume manually')),
                ('max_open_trades', models.PositiveIntegerField(default=3)),
                ('max_trades_per_symbol', models.PositiveIntegerField(default=1)),
                ('max_spread_pips', models.FloatField(default=3.0, help_text='Do not trade if spread exceeds this in pips')),
                ('trade_start_hour', models.PositiveIntegerField(default=0, help_text='UTC hour to start trading (0–23)', validators=[django.core.validators.MaxValueValidator(23)])),
                ('trade_end_hour', models.PositiveIntegerField(default=23, help_text='UTC hour to stop trading (0–23)', validators=[django.core.validators.MaxValueValidator(23)])),
                ('avoid_news_events', models.BooleanField(default=False, help_text='Pause trading around high-impact economic events')),
                ('news_buffer_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before/after news to avoid trading')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_rule', to='trading.tradingbot')),
            ],
            options={
                'verbose_name': 'Risk Rule',
                'verbose_name_plural': 'Risk Rules',
                'db_table': 'risk_rule',
            },
        ),
        migrations.CreateModel(
            name='DrawdownEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('pause', 'Bot Paused (drawdown_pause_percent hit)'), ('halt', 'Bot Halted (max_drawdown_percent hit)'), ('daily', 'Daily Loss Limit Hit'), ('resume', 'Bot Resumed')], max_length=10)),
                ('drawdown_percent', models.FloatField()),
                ('balance_at_event', models.DecimalField(decimal_places=2, max_digits=18)),
                ('peak_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('triggered_by', models.CharField(blank=True, help_text="Trade ID or 'daily_check' that triggered this event", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdown_events', to='trading.tradingbot')),
            ],
            options={
                'verbose_name': 'Drawdown Event',
                'verbose_name_plural': 'Drawdown Events',
                'db_table': 'risk_drawdown_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['bot', 'timestamp'], name='risk_drawdo_bot_id_51e91c_idx'), models.Index(fields=['event_type', 'timestamp'], name='risk_drawdo_event_t_b63897_idx')],
            },
        ),
    ]
