# Generated by Django 6.0.3 on 2026-03-17 18:10

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('strategy_type', models.CharField(choices=[('ma_crossover', 'Moving Average Crossover'), ('rsi_reversal', 'RSI Reversal'), ('breakout', 'Breakout Strategy'), ('mean_reversion', 'Mean Reversion'), ('custom', 'Custom Strategy')], default='ma_crossover', max_length=30)),
                ('plugin_path', models.CharField(help_text="Python dotted path to the strategy class, e.g. 'apps.strategies.plugins.ma_crossover.MACrossoverStrategy'", max_length=300)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text="e.g. ['EUR_USD', 'GBP_USD']")),
                ('timeframe', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('M30', '30 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '1 Day'), ('W1', '1 Week'), ('MN1', '1 Month')], default='H1', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='If True, other users can view (not edit) this strategy.')),
                ('last_win_rate', models.FloatField(blank=True, null=True)),
                ('last_profit_factor', models.FloatField(blank=True, null=True)),
                ('last_sharpe', models.FloatField(blank=True, null=True)),
                ('backtest_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'db_table': 'strategies_strategy',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'strategy_type'], name='strategies__user_id_92b1ee_idx'), models.Index(fields=['is_active'], name='strategies__is_acti_96bc90_idx'), models.Index(fields=['is_public'], name='strategies__is_publ_4ed3d4_idx')],
            },
        ),
    ]
