# Generated by Django 6.0.3 on 2026-03-17 18:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('M30', '30 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '1 Day'), ('W1', '1 Week'), ('MN1', '1 Month')], max_length=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('parameters_snapshot', models.JSONField(default=dict)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=10000, max_digits=18, validators=[django.core.validators.MinValueValidator(1)])),
                ('commission_per_lot', models.DecimalField(decimal_places=4, default=7.0, max_digits=10)),
                ('spread_pips', models.FloatField(default=1.5)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('progress', models.FloatField(default=0.0, help_text='0–100 completion percentage', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('final_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backtest Result',
                'verbose_name_plural': 'Backtest Results',
                'db_table': 'backtesting_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trade_index', models.PositiveIntegerField(help_text='Sequential trade number in this backtest')),
                ('symbol', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('exit_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('lot_size', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=18)),
                ('profit_pips', models.FloatField(default=0.0)),
                ('exit_reason', models.CharField(default='signal', max_length=30)),
                ('indicators', models.JSONField(blank=True, default=dict)),
                ('entry_time', models.DateTimeField(db_index=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtesting.backtestresult')),
            ],
            options={
                'verbose_name': 'Backtest Trade',
                'verbose_name_plural': 'Backtest Trades',
                'db_table': 'backtesting_trade',
                'ordering': ['entry_time'],
            },
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['user', 'status'], name='backtesting_user_id_2af45c_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['strategy', 'created_at'], name='backtesting_strateg_aff1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['symbol', 'timeframe'], name='backtesting_symbol_8e25dd_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['status', 'created_at'], name='backtesting_status_7bda4c_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['backtest', 'entry_time'], name='backtesting_backtes_49a5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['backtest', 'order_type'], name='backtesting_backtes_b75fcb_idx'),
        ),
    ]
