# Generated by Django 6.0.3 on 2026-03-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFetchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=5)),
                ('broker', models.CharField(max_length=30)),
                ('source', models.CharField(choices=[('oanda', 'OANDA'), ('mt5', 'MT5'), ('alpha_vantage', 'AlphaVantage')], default='oanda', max_length=30)),
                ('fetch_from', models.DateTimeField()),
                ('fetch_to', models.DateTimeField()),
                ('candles_fetched', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_data_fetchlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'broker'], name='market_data_symbol_ba5748_idx'), models.Index(fields=['created_at'], name='market_data_created_8b8bf3_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveTick',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('broker', models.CharField(choices=[('oanda', 'OANDA'), ('metatrader5', 'MetaTrader 5'), ('demo', 'Demo (Paper Trading)')], max_length=30)),
                ('bid', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ask', models.DecimalField(decimal_places=6, max_digits=18)),
                ('spread', models.DecimalField(decimal_places=6, max_digits=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Live Tick',
                'verbose_name_plural': 'Live Ticks',
                'db_table': 'market_data_livetick',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol_da00b1_idx'), models.Index(fields=['broker', 'symbol', '-timestamp'], name='market_data_broker_e89b3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('M30', '30 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '1 Day'), ('W1', '1 Week'), ('MN1', '1 Month')], max_length=5)),
                ('broker', models.CharField(choices=[('oanda', 'OANDA'), ('metatrader5', 'MetaTrader 5'), ('demo', 'Demo (Paper Trading)')], default='oanda', max_length=30)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=18)),
                ('high', models.DecimalField(decimal_places=6, max_digits=18)),
                ('low', models.DecimalField(decimal_places=6, max_digits=18)),
                ('close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('volume', models.BigIntegerField(default=0)),
                ('bid_open', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('bid_close', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ask_open', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ask_close', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('is_complete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Data (OHLCV)',
                'verbose_name_plural': 'Market Data (OHLCV)',
                'db_table': 'market_data_ohlcv',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='market_data_symbol_e89a50_idx'), models.Index(fields=['broker', 'symbol', 'timeframe'], name='market_data_broker_7bc639_idx'), models.Index(fields=['symbol', '-timestamp'], name='market_data_symbol_80cc88_idx')],
                'unique_together': {('symbol', 'timeframe', 'broker', 'timestamp')},
            },
        ),
    ]
